# -*- coding: utf-8 -*-
"""
Macedonian municipalities per the reorganization from 2004.
"""
from __future__ import unicode_literals

from django.utils.translation import ugettext_lazy as _

MK_MUNICIPALITIES = (
    ('AD', _('Aerodrom')),
    ('AR', _('Ara\u010dinovo')),
    ('BR', _('Berovo')),
    ('TL', _('Bitola')),
    ('BG', _('Bogdanci')),
    ('VJ', _('Bogovinje')),
    ('BS', _('Bosilovo')),
    ('BN', _('Brvenica')),
    ('BU', _('Butel')),
    ('VA', _('Valandovo')),
    ('VL', _('Vasilevo')),
    ('VV', _('Vev\u010dani')),
    ('VE', _('Veles')),
    ('NI', _('Vinica')),
    ('VC', _('Vrane\u0161tica')),
    ('VH', _('Vrap\u010di\u0161te')),
    ('GB', _('Gazi Baba')),
    ('GV', _('Gevgelija')),
    ('GT', _('Gostivar')),
    ('GR', _('Gradsko')),
    ('DB', _('Debar')),
    ('DA', _('Debarca')),
    ('DL', _('Del\u010devo')),
    ('DK', _('Demir Kapija')),
    ('DM', _('Demir Hisar')),
    ('DE', _('Dolneni')),
    ('DR', _('Drugovo')),
    ('GP', _('Gjor\u010de Petrov')),
    ('ZE', _('\u017delino')),
    ('ZA', _('Zajas')),
    ('ZK', _('Zelenikovo')),
    ('ZR', _('Zrnovci')),
    ('IL', _('Ilinden')),
    ('JG', _('Jegunovce')),
    ('AV', _('Kavadarci')),
    ('KB', _('Karbinci')),
    ('KX', _('Karpo\u0161')),
    ('VD', _('Kisela Voda')),
    ('KH', _('Ki\u010devo')),
    ('KN', _('Kon\u010de')),
    ('OC', _('Ko\u0107ani')),
    ('KY', _('Kratovo')),
    ('KZ', _('Kriva Palanka')),
    ('KG', _('Krivoga\u0161tani')),
    ('KS', _('Kru\u0161evo')),
    ('UM', _('Kumanovo')),
    ('LI', _('Lipkovo')),
    ('LO', _('Lozovo')),
    ('MR', _('Mavrovo i Rostu\u0161a')),
    ('MK', _('Makedonska Kamenica')),
    ('MD', _('Makedonski Brod')),
    ('MG', _('Mogila')),
    ('NG', _('Negotino')),
    ('NV', _('Novaci')),
    ('NS', _('Novo Selo')),
    ('OS', _('Oslomej')),
    ('OD', _('Ohrid')),
    ('PE', _('Petrovec')),
    ('PH', _('Peh\u010devo')),
    ('PN', _('Plasnica')),
    ('PP', _('Prilep')),
    ('PT', _('Probi\u0161tip')),
    ('RV', _('Radovi\u0161')),
    ('RN', _('Rankovce')),
    ('RE', _('Resen')),
    ('RO', _('Rosoman')),
    ('AJ', _('Saraj')),
    ('SL', _('Sveti Nikole')),
    ('SS', _('Sopi\u0161te')),
    ('SD', _('Star Dojran')),
    ('NA', _('Staro Nagori\u010dane')),
    ('UG', _('Struga')),
    ('RU', _('Strumica')),
    ('SU', _('Studeni\u010dani')),
    ('TR', _('Tearce')),
    ('ET', _('Tetovo')),
    ('CE', _('Centar')),
    ('CZ', _('Centar-\u017dupa')),
    ('CI', _('\u010cair')),
    ('CA', _('\u010ca\u0161ka')),
    ('CH', _('\u010ce\u0161inovo-Oble\u0161evo')),
    ('CS', _('\u010cu\u010der-Sandevo')),
    ('ST', _('\u0160tip')),
    ('SO', _('\u0160uto Orizari')),
)
